### ISSUE TITLE
TargetInfo struct fields non public

### ISSUE THREAD

**Issue by xanderio** [alexrsagen/rs-nfc1#1]
All fields of all structs which are used in the TargetInfo enum are non `pub` this makes it impossible to access e.g. the uid of a target. Is this an over side or indented?ri

**Comment by alexrsagen** [comment]
This was most likely an oversight, yes.

Naturally, during development and testing of the package making such fields public was not neccessary, but obviously these fields need to be public for it to be used as a library.

I will see if there is anything else that needs making public and then merge the request later today.

**Comment by alexrsagen** [comment]
v0.2.1 released, containing your patch.

Thanks for the contribution. Feel free to let me know how my project is useful to you or what you're working on 😄

**Comment by xanderio** [comment]
Could you upload 0.2.1 to crates.io?

**Comment by alexrsagen** [comment]
Published 0.3.0 just now, containing updated `nfc1-sys` version with linux build fixes.

Let me know how it works for you.
