### ISSUE TITLE
Rustfmt

### ISSUE THREAD

**Issue by xanderio** [alexrsagen/rs-nfc1#3]
This project is not formatted with rustfmt, or it is but to config is not included in the repository.

**Comment by alexrsagen** [comment]
Honest question, does the fact that it's not formatted with rustfmt hinder or bother you in any way?

If not, then I can add rustfmt to my development workflow and format the code another time.

**Comment by xanderio** [comment]
It does not hinder me, its just slightly annoying to have to remove the on-save out formating each time i work on our of your crates.
