### ISSUE TITLE
nfc1::Error dosn't implement std::error::Error

### ISSUE THREAD

**Issue by xanderio** [alexrsagen/rs-nfc1#5]
Implementing the Trait would allow for easy use of e.g. anyhow and co.

**Comment by alexrsagen** [comment]
For now it implements `std::io::Error`, which in turn implements `std::error::Error`.

Does this suffice? 🙂

**Comment by hgonomeg** [comment]
> For now it implements `std::io::Error`, which in turn implements `std::error::Error`.
> 
> Does this suffice? slightly_smiling_face

...except it doesn't.
It implements `From<Error>` which IS NOT the same.
The trait `std::error::Error` is not implemented for `nfc1::Error`, nor is `std::fmt::Display` which is required for `std::error::Error`.
This needs to be reopened.

**Comment by alexrsagen** [comment]
Thanks for the feedback @hgonomeg, this is exactly what I needed to hear.

Will make it happen. 👍

**Comment by hgonomeg** [comment]
@alexrsagen Thank you very much for the quick reaction. It has been very helpful.
