### ISSUE TITLE
Build failed when used as dependency with default-features = false

### ISSUE THREAD

**Issue by riklus** [alexrsagen/rs-nfc1#9]
I added nfc1 as a dependency with:

```
$ cargo add nfc1 --no-default-features   
```

Then ran the script.

```
$ cargo run
    Blocking waiting for file lock on build directory
   Compiling nfc1-sys v0.3.4
   Compiling nfc1 v0.5.1
error[E0432]: unresolved imports `nfc1_sys::pn53x_transceive`, `nfc1_sys::pn53x_read_register`, `nfc1_sys::pn53x_write_register`
  --> /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/nfc1-0.5.1/src/device.rs:23:2
   |
23 |     pn53x_transceive,
   |     ^^^^^^^^^^^^^^^^ no `pn53x_transceive` in the root
24 |     pn53x_read_register,
   |     ^^^^^^^^^^^^^^^^^^^ no `pn53x_read_register` in the root
25 |     pn53x_write_register,
   |     ^^^^^^^^^^^^^^^^^^^^ no `pn53x_write_register` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `nfc1` due to previous error
```

It's referencing these lines:

https://github.com/alexrsagen/rs-nfc1/blob/258ae6a32890cee72858786e021589df0bbe34b1/src/device.rs#L23-L25

#### Probable cause

This is likely because when the default features are disabled, the default drivers in nfc1-sys are being disabled too:

https://github.com/alexrsagen/rs-nfc1-sys/blob/a8e2c8a999ca71e93c7af9e098218bc85717b219/Cargo.toml#L26-L32

Therefore`build.rs` does not genereates the bindings for the drivers.

#### Possible fix

When the `--no-default-features` flag is used the `pn53x_*` functions should not be included.

I suggest excluding these imports when the `--no-default-features` flag is enabled:

https://github.com/alexrsagen/rs-nfc1-sys/blob/a8e2c8a999ca71e93c7af9e098218bc85717b219/Cargo.toml#L26-L32

**Comment by alexrsagen** [comment]
If you're not using the default features, you need to add every feature you need explicitly, as explained here: https://doc.rust-lang.org/cargo/reference/features.html

You need the "drivers" feature to generate bindings to driver-specific functions.

Your dependency line in Cargo.toml might look like:
```toml
nfc1 = { version = "0.5", default-features = false, features = ["drivers"] }
```

Does this solve the issue?

**Comment by riklus** [comment]
Adding the `drivers` features "solves" the problem, in the sense that it links the drivers and generates bindings for the functions mentioned in the issue.
But I do not need any drivers related for the `pn53x` because I do not need to use the `pn53x_*` functions.

I think that the user shoul be allowed to link against the library without linking any vendor specific drivers, i.e. by importing the package like this: `nfc1 = { version = "0.5", default-features = false }`. 

The documentation page that you linked provides an [example](https://doc.rust-lang.org/cargo/reference/features.html#dependency-features) in which the dependency `jpeg-decoder` is added having all the default features disabled, with no other dependency specified.

**Comment by alexrsagen** [comment]
Thanks for clarifying.

I agree this *should* work. I'll look into what code depends on the driver-specific functions and add `#[cfg(feature = "drivers")]` where applicable.

I'll let you know when building without `drivers` feature works fine.
